# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=10, verbose_name='Cep')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
            ],
        ),
    ]
